// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf0exjeSf6IQcoGAOnKmVeO8g3pk_hBVY',
    appId: '1:29666587146:web:3c1112a124f51e921125f3',
    messagingSenderId: '29666587146',
    projectId: 'bharathbiomed-14368',
    authDomain: 'bharathbiomed-14368.firebaseapp.com',
    storageBucket: 'bharathbiomed-14368.firebasestorage.app',
    measurementId: 'G-6GFPQWNLH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBbqbQwAsiaGqPy9CGBBM8EXBtOM--gvM',
    appId: '1:29666587146:android:3c2e6483de7c32ff1125f3',
    messagingSenderId: '29666587146',
    projectId: 'bharathbiomed-14368',
    storageBucket: 'bharathbiomed-14368.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEa_m7-zsK4llLzTzGLffbyKorypwEsr8',
    appId: '1:29666587146:ios:dc9191a3c3dc8ecf1125f3',
    messagingSenderId: '29666587146',
    projectId: 'bharathbiomed-14368',
    storageBucket: 'bharathbiomed-14368.firebasestorage.app',
    iosBundleId: 'com.syncosolve.bharathbiomedpharma',
  );
}
