// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxrdRbnjEY_HeGeu5snnzkfrXDKcXYPL8',
    appId: '1:830540132112:web:f5fdbb8365e3bfbbed3f95',
    messagingSenderId: '830540132112',
    projectId: 'bharathbiomedpharma-6c6c3',
    authDomain: 'bharathbiomedpharma-6c6c3.firebaseapp.com',
    storageBucket: 'bharathbiomedpharma-6c6c3.firebasestorage.app',
    measurementId: 'G-SSHM1PXVNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7iP0Kq52SuNZHQVKfwSlCDdGoxNazW4',
    appId: '1:830540132112:android:e222df6854b8bf5eed3f95',
    messagingSenderId: '830540132112',
    projectId: 'bharathbiomedpharma-6c6c3',
    storageBucket: 'bharathbiomedpharma-6c6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD34UCGRAzuLkcTBnpGSxBwETShloKPr-I',
    appId: '1:830540132112:ios:5be2e7cbb6fb6799ed3f95',
    messagingSenderId: '830540132112',
    projectId: 'bharathbiomedpharma-6c6c3',
    storageBucket: 'bharathbiomedpharma-6c6c3.firebasestorage.app',
    iosBundleId: 'com.syncosolve.bharathbiomedpharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD34UCGRAzuLkcTBnpGSxBwETShloKPr-I',
    appId: '1:830540132112:ios:5be2e7cbb6fb6799ed3f95',
    messagingSenderId: '830540132112',
    projectId: 'bharathbiomedpharma-6c6c3',
    storageBucket: 'bharathbiomedpharma-6c6c3.firebasestorage.app',
    iosBundleId: 'com.syncosolve.bharathbiomedpharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxrdRbnjEY_HeGeu5snnzkfrXDKcXYPL8',
    appId: '1:830540132112:web:0f1c6602e0136b33ed3f95',
    messagingSenderId: '830540132112',
    projectId: 'bharathbiomedpharma-6c6c3',
    authDomain: 'bharathbiomedpharma-6c6c3.firebaseapp.com',
    storageBucket: 'bharathbiomedpharma-6c6c3.firebasestorage.app',
    measurementId: 'G-8G5Q3M2GHC',
  );
}
