import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';

import 'order.dart';

/// Generated by the `generateInvoice` Cloud Function once an [Order] has
/// been dispatched — [items]/[totalValue] are copied from the order at
/// generation time (a later edit to the order, which shouldn't happen post-
/// dispatch anyway, must never silently change an already-issued invoice).
/// [invoiceNumber] is assigned by a race-safe counter in that Cloud
/// Function, not derived from [id].
class Invoice extends Equatable {
  final String id;
  final String orderId;
  final String invoiceNumber;
  final String agencyId;
  final String agencyName;
  final List<OrderItem> items;
  final double totalValue;
  final DateTime? issuedAt;

  const Invoice({
    required this.id,
    required this.orderId,
    required this.invoiceNumber,
    required this.agencyId,
    required this.agencyName,
    required this.items,
    required this.totalValue,
    this.issuedAt,
  });

  factory Invoice.fromJson(String id, Map<String, dynamic> json) {
    debugPrint('Invoice.fromJson: parsing invoice id=$id');
    return Invoice(
      id: id,
      orderId: json['orderId'] as String? ?? '',
      invoiceNumber: json['invoiceNumber'] as String? ?? '',
      agencyId: json['agencyId'] as String? ?? '',
      agencyName: json['agencyName'] as String? ?? '',
      items: (json['items'] as List? ?? const [])
          .map((item) => OrderItem.fromJson(Map<String, dynamic>.from(item as Map)))
          .toList(),
      totalValue: (json['totalValue'] as num?)?.toDouble() ?? 0,
      issuedAt: _dateFromAny(json['issuedAt']),
    );
  }

  static DateTime? _dateFromAny(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    try {
      return (value as dynamic).toDate() as DateTime;
    } catch (_) {
      return null;
    }
  }

  @override
  List<Object?> get props =>
      [id, orderId, invoiceNumber, agencyId, agencyName, items, totalValue, issuedAt];
}
