import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';

import 'order.dart';

/// `unpaid` (generated here) -> `partial` (one or more payments recorded,
/// short of [Invoice.grandTotal]) -> `paid` (fully covered). Never a hard
/// gate on anything — see `recordPayment` (Cloud Function) and
/// `Invoice.isOverdue`, which is a derived flag, not a fourth status, so an
/// overdue-then-paid invoice doesn't need a status transition back.
enum PaymentStatus { unpaid, partial, paid }

PaymentStatus paymentStatusFromString(String? value) {
  switch (value) {
    case 'partial':
      return PaymentStatus.partial;
    case 'paid':
      return PaymentStatus.paid;
    default:
      return PaymentStatus.unpaid;
  }
}

String paymentStatusToJson(PaymentStatus status) => switch (status) {
      PaymentStatus.unpaid => 'unpaid',
      PaymentStatus.partial => 'partial',
      PaymentStatus.paid => 'paid',
    };

/// Generated by the `generateInvoice` Cloud Function once an [Order] has
/// been dispatched — [items]/[totalValue] are copied from the order at
/// generation time (a later edit to the order, which shouldn't happen post-
/// dispatch anyway, must never silently change an already-issued invoice).
/// [invoiceNumber] is assigned by a race-safe counter in that Cloud
/// Function, not derived from [id].
///
/// [taxLabel]/[taxRate] are copied from `TenantConfig`
/// (`functions/src/generatedTenantConfig.ts`'s twin of it) **at generation
/// time**, not read live — if a tenant's tax rate changes later, past
/// invoices must keep showing the rate that actually applied when they
/// were issued, not be silently reinterpreted under a new rate.
class Invoice extends Equatable {
  final String id;
  final String orderId;
  final String invoiceNumber;
  final String agencyId;
  final String agencyName;
  final List<OrderItem> items;
  final double totalValue;
  final String taxLabel;
  final double taxRate;
  final double taxAmount;
  final double grandTotal;
  final PaymentStatus paymentStatus;
  final double amountPaid;
  final DateTime? dueDate;
  final DateTime? issuedAt;

  const Invoice({
    required this.id,
    required this.orderId,
    required this.invoiceNumber,
    required this.agencyId,
    required this.agencyName,
    required this.items,
    required this.totalValue,
    this.taxLabel = '',
    this.taxRate = 0,
    this.taxAmount = 0,
    this.grandTotal = 0,
    this.paymentStatus = PaymentStatus.unpaid,
    this.amountPaid = 0,
    this.dueDate,
    this.issuedAt,
  });

  /// Whether this invoice's remaining balance is past [dueDate] — derived,
  /// not a stored status (see [PaymentStatus]'s doc comment for why),
  /// re-evaluated against the current time every time it's read.
  bool get isOverdue {
    if (paymentStatus == PaymentStatus.paid) return false;
    if (dueDate == null) return false;
    return DateTime.now().isAfter(dueDate!);
  }

  double get balanceDue => grandTotal - amountPaid;

  factory Invoice.fromJson(String id, Map<String, dynamic> json) {
    debugPrint('Invoice.fromJson: parsing invoice id=$id');
    final totalValue = (json['totalValue'] as num?)?.toDouble() ?? 0;
    return Invoice(
      id: id,
      orderId: json['orderId'] as String? ?? '',
      invoiceNumber: json['invoiceNumber'] as String? ?? '',
      agencyId: json['agencyId'] as String? ?? '',
      agencyName: json['agencyName'] as String? ?? '',
      items: (json['items'] as List? ?? const [])
          .map((item) => OrderItem.fromJson(Map<String, dynamic>.from(item as Map)))
          .toList(),
      totalValue: totalValue,
      taxLabel: json['taxLabel'] as String? ?? '',
      taxRate: (json['taxRate'] as num?)?.toDouble() ?? 0,
      taxAmount: (json['taxAmount'] as num?)?.toDouble() ?? 0,
      // Legacy invoices generated before tax/payment tracking existed have
      // no grandTotal stored — fall back to the pre-tax total so they still
      // display a sane figure instead of 0.
      grandTotal: (json['grandTotal'] as num?)?.toDouble() ?? totalValue,
      paymentStatus: paymentStatusFromString(json['paymentStatus'] as String?),
      amountPaid: (json['amountPaid'] as num?)?.toDouble() ?? 0,
      dueDate: _dateFromAny(json['dueDate']),
      issuedAt: _dateFromAny(json['issuedAt']),
    );
  }

  static DateTime? _dateFromAny(dynamic value) {
    if (value == null) return null;
    if (value is DateTime) return value;
    try {
      return (value as dynamic).toDate() as DateTime;
    } catch (_) {
      return null;
    }
  }

  @override
  List<Object?> get props => [
        id,
        orderId,
        invoiceNumber,
        agencyId,
        agencyName,
        items,
        totalValue,
        taxLabel,
        taxRate,
        taxAmount,
        grandTotal,
        paymentStatus,
        amountPaid,
        dueDate,
        issuedAt,
      ];
}
